FROM --platform=linux/amd64 nginx:latest

COPY nginx-selfsigned.crt /etc/nginx/ssl/nginx-selfsigned.crt
COPY nginx-selfsigned.key /etc/nginx/ssl/nginx-selfsigned.key

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 443
HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl -k -f https://localhost/ || exit 1

CMD ["nginx", "-g", "daemon off;"]

