services:
 dynamodb-local:
   #command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
   command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb-local
   ports:
     - "8989:8000"
   #volumes:
   #  - "./docker/dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal